language: node_js
node_js:
  - "10.14.1"
before_install:
  - npm i -g npm@6.4.1
services:
  - postgresql
env:
  - TEST_DB_USER=root
  - TEST_DB_PASSWORD=null
before_script:
  - psql -c 'create databaseslack_server_test;' -U postgres