version: "3"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432"
  app:
    image: hypechat4/hypechat
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: bash -c "sleep 20; npx sequelize db:create; npx sequelize db:migrate; node src/app.js"
    environment:
        DOCKER: 1
    
