version: "3"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=slack_server
  app:
    image: hypechat4/hypechat
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=slack_server
