/register:
    post:
        body:
            type: UserRequest
            example: !include examples/usersRegisterRequest.json
        responses:
            200:
                body:
                    type: User
                    example: !include examples/usersRegisterResponse.json
            500:
                !include errorResponse.raml

